trigger:
  branches:
    include:
      - desarrollo
      - main

# Agregar parámetro de entorno
parameters:
  - name: entorno
    displayName: "Selecciona el entorno"
    type: string
    default: "blue"
    values:
      - blue
      - green

# Definir las variables
variables:
  - name: BRANCH_NAME
    value: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]

# Usar expresiones para asignar valores de ECR, Service, Task y Cluster
  - ${{ if eq(parameters.entorno, 'blue') }}:
      - name: TARGET_ECR
        value: 'ecr-blue'
      - name: TARGET_SERVICE
        value: 'service-blue'
      - name: TARGET_CLUSTER
        value: 'cluster-blue'
      - name: TARGET_TASK
        value: 'task-blue'
  - ${{ if eq(parameters.entorno, 'green') }}:
      - name: TARGET_ECR
        value: 'ecr-green'
      - name: TARGET_SERVICE
        value: 'service-green'
      - name: TARGET_CLUSTER
        value: 'cluster-green'
      - name: TARGET_TASK
        value: 'task-green'

  # Cargar grupo de variables dependiendo del parámetro 'entorno'
  - ${{ if eq(parameters.entorno, 'blue') }}:
      - group: blue-vars-group
  - ${{ if eq(parameters.entorno, 'green') }}:
      - group: green-vars-group

# Repositorios a usar
resources:
  repositories:
    - repository: plantillas
      name: Inicio DevOps Johan/templates
      type: git

# Stages con el template
stages:
  - stage: Deploy_Back
    displayName: 'Ejecutar Deploy Back'
    jobs:
      - job: Deploy
        displayName: Despliegue
        steps:
          - template: ci-cd-back.yml@plantillas
